#!/bin/bash

set -e

getent group twitterconnector >/dev/null || groupadd -r twitterconnector
getent passwd twitterconnector > /dev/null || useradd -c "twitterconnector" -s /bin/bash -g twitterconnector -d /var/lib/TwitterConnector twitterconnector 2> /dev/null || :

